import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const root=process.cwd();
const marketApi=require(path.join(root,'dist/storymemory-pack-marketplace-runtime.js'));
const lifeApi=require(path.join(root,'dist/storymemory-pack-lifecycle-runtime.js'));
const catalog=JSON.parse(fs.readFileSync(path.join(root,'dist/packs/marketplace-catalog-v1.json'),'utf8')).listings;
const artifacts=new Map();
for(const x of catalog){for(const v of x.versions||[]){const p=path.join(root,'dist',v.artifactUri);if(fs.existsSync(p))artifacts.set(v.artifactUri,JSON.parse(fs.readFileSync(p,'utf8')))}}
const market=marketApi.createStoryMemoryPackMarketplaceRuntime({artifactLoader:async uri=>structuredClone(artifacts.get(uri))});
market.replaceCatalog(catalog);
const life=lifeApi.createStoryMemoryPackLifecycleRuntime({marketplace:market,artifactLoader:async uri=>structuredClone(artifacts.get(uri))});
const packId='pack:odyssey:korean-alias-public:v1';
const before=market.getListing(packId);
const checks={};
checks.contract=life.contract.schema==='storymemory-pack-lifecycle-1.0'&&life.contract.marketplaceStage==='M5';
checks.versionHistory=life.versionHistory(packId).map(x=>x.version).join(',')==='1.0.0';
const rating=await life.ratePack(packId,'1.0.0',{overallRating:5,accuracyRating:5,citationRating:4,reviewText:'alias retrieval improved'});
checks.ratingSaved=rating.overallRating===5;
const summary=await life.ratingSummary(packId,'1.0.0');
checks.ratingSummary=summary.ratingCount===1&&summary.overallAverage===5;
let ratingRejected=false;try{await life.ratePack(packId,'1.0.0',{overallRating:6})}catch(e){ratingRejected=e.message==='PACK_RATING_OUT_OF_RANGE'}checks.ratingRangeGate=ratingRejected;
const fb=await life.submitFeedback(packId,'1.0.0',{kind:'correction',sourceLocator:'odyssey:book:04:s1:row:002',message:'Helen should expand to 헬레네',proposedCorrection:{alias:'헬렌',canonical:'헬레네'}});
checks.feedbackSaved=fb.feedbackKind==='correction'&&fb.sourceLocator.includes('book:04');
let noLocator=false;try{await life.submitFeedback(packId,'1.0.0',{kind:'error',message:'bad'})}catch(e){noLocator=e.message==='PACK_FEEDBACK_SOURCE_LOCATOR_REQUIRED'}checks.feedbackLocatorGate=noLocator;
let bodyRejected=false;try{await life.submitFeedback(packId,'1.0.0',{kind:'correction',sourceLocator:'x',message:'bad',sourceText:'full source text'})}catch(e){bodyRejected=e.message==='PACK_FEEDBACK_SOURCE_BODY_FORBIDDEN'}checks.feedbackSourceBodyGate=bodyRejected;
const prop=await life.proposeVersion(packId,{proposedVersion:'1.1.0',parentVersion:'1.0.0',artifactUri:'packs/odyssey-korean-alias-public-v1.json',artifactFingerprint:'fnv1a:newfixture',changelog:'Add another transliteration hint'});
checks.proposalDraft=prop.proposalStatus==='draft'&&prop.proposedVersion==='1.1.0';
checks.noSilentLatestMutation=market.getListing(packId).latestVersion==='1.0.0'&&market.getListing(packId).versions.length===1;
const submitted=await life.submitVersionProposal(prop.id);
checks.proposalReviewFlow=submitted.proposalStatus==='pending_review';
let oldRejected=false;try{await life.proposeVersion(packId,{proposedVersion:'1.0.0',artifactUri:'x',artifactFingerprint:'y',changelog:'bad'})}catch(e){oldRejected=['PACK_VERSION_MUST_ADVANCE','PACK_VERSION_ALREADY_EXISTS'].includes(e.message)}checks.versionAdvanceGate=oldRejected;
const fork=await life.createFork(packId,{newPackId:'pack:user:odyssey-alias-fork:v1',name:'My Odyssey Alias Fork',creatorId:'user:test'});
checks.forkPrivate=fork.listing.visibility==='private'&&fork.listing.publicationStatus==='draft';
checks.forkLocalDraft=fork.persisted===false&&fork.listing.versions[0].artifactUri===''&&life.status().localForkDraftCount===1;
checks.forkLineage=fork.listing.listingMetadata.lineage.parentPackId===packId&&fork.listing.listingMetadata.lineage.parentVersion==='1.0.0';
checks.forkNotVerified=fork.listing.versions[0].declaredTrustTier==='auto-generated'&&fork.listing.attestations.length===0&&fork.artifact.metadata.verifiedInherited===false;
checks.parentImmutable=JSON.stringify(before)===JSON.stringify(market.getListing(packId));
checks.forkDiscoverable=life.listForks(packId).some(x=>x.packId==='pack:user:odyssey-alias-fork:v1');
let writerRequired=false;try{await life.persistFork(fork.listing.packId)}catch(e){writerRequired=e.message==='PACK_FORK_ARTIFACT_WRITER_REQUIRED'}checks.forkWriterRequired=writerRequired;
const persistedCalls=[];
life.setArtifactWriter(async (artifact,{listing})=>({artifactUri:`packs/${listing.packId.replaceAll(':','-')}.json`,artifactFingerprint:'sha256:stored-fork-fixture'}));
life.setProvider({async createForkDraft(payload){persistedCalls.push(structuredClone(payload));return payload.listing}});
const persistedFork=await life.persistFork(fork.listing.packId);
checks.forkPersistAfterArtifactWrite=persistedFork.persisted===true&&persistedFork.listing.versions[0].artifactUri.startsWith('packs/')&&persistedFork.listing.versions[0].artifactFingerprint==='sha256:stored-fork-fixture'&&persistedCalls.length===1;
checks.forkRegistryAfterWriter=persistedCalls[0].version.artifactUri===persistedFork.listing.versions[0].artifactUri&&persistedCalls[0].version.artifactFingerprint==='sha256:stored-fork-fixture';
const pass=Object.values(checks).every(Boolean);
const result={schema:'sm090-pack-lifecycle-runtime-test-1.1',pass,checks,summary:{publishedPackLatest:market.getListing(packId).latestVersion,ratingSummary:summary,feedbackCount:(await life.listMyFeedback(packId)).length,proposalStatus:submitted.proposalStatus,forkId:fork.listing.packId,forkVisibility:fork.listing.visibility,forkPersisted:persistedFork.persisted,persistedForkCalls:persistedCalls.length}};
fs.writeFileSync(path.join(root,'QA_EVIDENCE/SM090_PACK_LIFECYCLE_RUNTIME_RESULT.json'),JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result,null,2));
if(!pass)process.exit(1);
