const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const u=require(path.join(ROOT,'dist/storymemory-universal-source-runtime.js'));
const m=require(path.join(ROOT,'dist/storymemory-pack-marketplace-runtime.js'));
const v=require(path.join(ROOT,'dist/storymemory-pack-verification-runtime.js'));
(async()=>{
const rt=u.createStoryMemoryUniversalSourceRuntime();
const market=m.createStoryMemoryPackMarketplaceRuntime({universalRuntime:rt});
market.replaceCatalog([{packId:'pack:test:knowledge',name:'Test Knowledge',packType:'knowledge',creatorId:'creator',visibility:'public',pricingMode:'free',publicationStatus:'published',latestVersion:'1.1.0',sourceTextIncluded:false,rightsDeclaration:{redistributionAllowed:true},compatibilitySummary:{sourceFingerprint:'fp-1'},permissions:{forkAllowed:true},versions:[{packId:'pack:test:knowledge',version:'1.0.0',schemaVersion:'storymemory-precision-pack-1.0',artifactUri:'x',declaredTrustTier:'expert',sourceMatchMode:'exact-fingerprint',compatibility:{sourceFingerprint:'fp-1'},rights:{sourceTextIncluded:false}},{packId:'pack:test:knowledge',version:'1.1.0',schemaVersion:'storymemory-precision-pack-1.0',artifactUri:'y',artifactFingerprint:'af-110',declaredTrustTier:'expert',sourceMatchMode:'exact-fingerprint',compatibility:{sourceFingerprint:'fp-1'},rights:{sourceTextIncluded:false}}],attestations:[]}]);
const fixed=Date.parse('2026-08-27T06:00:00Z');const verify=v.createStoryMemoryPackVerificationRuntime({universalRuntime:rt,marketplaceRuntime:market,now:()=>fixed});
await rt.ingest({sourceId:'doc:test',sourceType:'document',revision:'1',fingerprint:'fp-1',language:'ko',pages:[{page:1,blocks:[{text:'계약 기간은 30일이다.',kind:'paragraph'}]}]});
const source=rt.getSource('doc:test'),locator=source.firstLocator;
const base={attestationId:'att-1',packId:'pack:test:knowledge',version:'1.0.0',tier:'expert',sourceFingerprint:'fp-1',verificationScope:{claims:['duration']},attestationStatus:'valid',issuedAt:'2026-08-01T00:00:00Z',expiresAt:'2027-08-01T00:00:00Z',verifierId:'expert-1',verifierDisplayName:'Expert One',verifierKind:'expert',verifierStatus:'active',credentialId:'cred-1',credentialType:'professional',credentialIssuer:'Issuer',credentialStatus:'active',credentialValidFrom:'2026-01-01T00:00:00Z',credentialValidUntil:'2027-12-31T00:00:00Z',credentialAuthorityScope:{tiers:['expert'],packTypes:['knowledge']},requestId:'req-1',requestStatus:'approved'};
const checks=[];const ok=(name,pass,detail)=>{checks.push({name,pass:Boolean(pass),detail});if(!pass)throw new Error(name+':'+JSON.stringify(detail))};
verify.replaceProgram([base]);
let s=verify.getStatus('pack:test:knowledge','1.0.0',source);ok('expert exact version/fingerprint trusted',s.trusted&&s.effectiveTrustTier==='expert',s);
s=verify.getStatus('pack:test:knowledge','1.1.0',source);ok('new version does not inherit',!s.trusted,s);
s=verify.getStatus('pack:forked','0.1.0',source);ok('fork does not inherit',!s.trusted,s);
s=verify.getStatus('pack:test:knowledge','1.0.0',{...source,fingerprint:'fp-other'});ok('fingerprint mismatch fails',!s.trusted,s);
verify.replaceProgram([{...base,expiresAt:'2026-08-20T00:00:00Z'}]);ok('expired attestation fails',!verify.getStatus('pack:test:knowledge','1.0.0',source).trusted,verify.getStatus('pack:test:knowledge','1.0.0',source));
verify.replaceProgram([{...base,credentialStatus:'revoked'}]);ok('revoked credential fails',!verify.getStatus('pack:test:knowledge','1.0.0',source).trusted,verify.getStatus('pack:test:knowledge','1.0.0',source));
verify.replaceProgram([{...base,verifierStatus:'suspended'}]);ok('suspended verifier fails',!verify.getStatus('pack:test:knowledge','1.0.0',source).trusted,verify.getStatus('pack:test:knowledge','1.0.0',source));
verify.replaceProgram([base]);
const official={...base,attestationId:'att-official',tier:'official',verifierId:'publisher-1',verifierDisplayName:'Publisher One',verifierKind:'publisher',credentialId:'cred-official',credentialAuthorityScope:{tiers:['official'],packTypes:['knowledge']},requestId:'req-official'};
verify.replaceProgram([official]);
s=verify.getStatus('pack:test:knowledge','1.0.0',source);ok('official publisher exact version/fingerprint trusted',s.trusted&&s.effectiveTrustTier==='official',s);
verify.replaceProgram([{...official,verifierKind:'expert'}]);s=verify.getStatus('pack:test:knowledge','1.0.0',source);ok('official cannot be self-issued by expert kind',!s.trusted,s);
verify.replaceProgram([base]);
const pack={schema:'storymemory-precision-pack-1.0',id:'pack:test:knowledge',name:'Test Knowledge',kind:'knowledge',version:'1.0.0',trustTier:'expert',compatibility:{mode:'exact-fingerprint',sourceFingerprint:'fp-1'},rights:{sourceTextIncluded:false},payload:{knowledge:[{id:'k1',text:'계약 기간은 30일이다.',sourceRefs:[locator]}]}};
const attached=rt.attachPack('doc:test',pack);ok('attach receives expert attestation',attached.trustAttested&&attached.trustTier==='expert',attached);
const a=await rt.answer({question:'계약 기간은?',sourceId:'doc:test',trustMode:'STRICT'});ok('verified provenance requires source evidence',a.provenance?.label==='VERIFIED',a.provenance);
ok('popularity cannot create trust',verify.contract.popularityCreatesTrust===false&&verify.contract.ratingCreatesTrust===false,{rating:5,installs:999999,sales:999999});
const out={schema:'sm092-verification-runtime-test-1.0',pass:checks.every(x=>x.pass),checks,status:verify.status()};fs.writeFileSync(path.join(__dirname,'SM092_PACK_VERIFICATION_RUNTIME_RESULT.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
